#!/usr/bin/env python3
"""Export targeted rerun manifests for paper-critical lanes.

The source manifest remains unchanged. For each lane, this script writes a JSONL
manifest containing only cases that are missing, `not_run`, or errored in that
lane's result file. The output can be passed to the existing crossmodel runners
with a fresh output directory.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import paper_run_status


DEFAULT_OUT_DIR = Path("data/eval/rerun_manifests/lm4sci_20260623")


COMMANDS = {
    "gemini-3.1-pro bare": (
        "python3.11 scripts/crossmodel_eval.py gemini-3.1-pro {manifest} "
        "data/eval/crossmodel_reruns/gemini-3.1-pro_flashfail_lm4sci_rerun"
    ),
    "opus-4.7 bare": (
        "python3.11 scripts/crossmodel_eval.py opus-4.7 {manifest} "
        "data/eval/crossmodel_reruns/opus-4.7_flashfail_lm4sci_rerun"
    ),
    "gpt-5.5 bare old path": (
        "python3.11 scripts/crossmodel_eval.py gpt-5.5 {manifest} "
        "data/eval/crossmodel/gpt-5.5_flashfail_responses_medium_lm4sci "
        "--temperature 0.0 --reasoning-effort medium"
    ),
    "v4-pro answerer + v4-pro reader": (
        "python3.11 scripts/crossmodel_harness.py v4-pro v4-pro {manifest} "
        "data/eval/crossmodel_harness_reruns/v4-pro__reader_v4-pro_lm4sci_rerun"
    ),
    "v4-pro answerer + v4-flash reader": (
        "python3.11 scripts/crossmodel_harness.py v4-pro v4-flash {manifest} "
        "data/eval/crossmodel_harness_reruns/v4-pro__reader_v4-flash_lm4sci_rerun"
    ),
    "gemini-3.1-pro answerer + v4-pro reader": (
        "python3.11 scripts/crossmodel_harness.py gemini-3.1-pro v4-pro {manifest} "
        "data/eval/crossmodel_harness_reruns/gemini-3.1-pro__reader_v4-pro_lm4sci_rerun"
    ),
    "opus-4.8 answerer + v4-pro reader": (
        "python3.11 scripts/crossmodel_harness.py opus-4.8 v4-pro {manifest} "
        "data/eval/crossmodel_harness_reruns/opus-4.8__reader_v4-pro_lm4sci_rerun"
    ),
    "gpt-5.5 answerer + v4-pro reader": (
        "OPENAI_REASONING_EFFORT=medium python3.11 scripts/crossmodel_harness.py gpt-5.5 v4-pro "
        "{manifest} data/eval/crossmodel_harness/gpt-5.5__reader_v4-pro_responses_medium_lm4sci"
    ),
}


def slugify(text: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_").lower()
    return slug or "lane"


def manifest_by_case_id(path: Path) -> dict[str, dict]:
    rows = paper_run_status.read_jsonl(path)
    return {row["case_id"]: row for row in rows}


def incomplete_case_ids(lane: paper_run_status.Lane, manifest_rows: dict[str, dict]) -> list[str]:
    if lane.status in {"missing", "provisional"}:
        return list(manifest_rows)
    result_rows = paper_run_status.read_jsonl(lane.path)
    by_case = {row.get("case_id"): row for row in result_rows if row.get("case_id")}
    ids: list[str] = []
    for case_id in manifest_rows:
        row = by_case.get(case_id)
        if row is None:
            ids.append(case_id)
        elif row.get("score") == "not_run" or row.get("error"):
            ids.append(case_id)
    return ids


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            import json

            handle.write(json.dumps(row, sort_keys=True) + "\n")


def remove_stale_jsonl(out_dir: Path) -> None:
    if not out_dir.exists():
        return
    for path in out_dir.glob("*.jsonl"):
        path.unlink()


def export_manifests(out_dir: Path, include_empty: bool = False) -> list[dict[str, object]]:
    remove_stale_jsonl(out_dir)
    manifest_rows = manifest_by_case_id(paper_run_status.MANIFEST)
    exports: list[dict[str, object]] = []
    for lane in paper_run_status.LANES:
        case_ids = incomplete_case_ids(lane, manifest_rows)
        if not case_ids and not include_empty:
            continue
        out_path = out_dir / f"{slugify(lane.name)}.jsonl"
        rows = [manifest_rows[case_id] for case_id in case_ids]
        write_jsonl(out_path, rows)
        exports.append(
            {
                "lane": lane.name,
                "kind": lane.kind,
                "count": len(rows),
                "manifest": str(out_path),
                "command": COMMANDS.get(lane.name, "").format(manifest=out_path),
                "caveat": lane.caveat,
            }
        )
    return exports


def write_readme(out_dir: Path, exports: list[dict[str, object]]) -> Path:
    path = out_dir / "README.md"
    lines = [
        "# LM4Sci Targeted Rerun Manifests",
        "",
        "Generated by:",
        "",
        "```bash",
        "python3.11 scripts/export_paper_rerun_manifests.py",
        "```",
        "",
        "Each manifest contains cases that are missing, `not_run`, or errored in its corresponding lane.",
        "Run commands should be executed only after the relevant API quota/secrets are available.",
        "",
        "| Lane | Count | Manifest | Suggested command | Caveat |",
        "|---|---:|---|---|---|",
    ]
    for item in exports:
        command = str(item["command"]).replace("|", "\\|")
        lines.append(
            f"| {item['lane']} | {item['count']} | `{item['manifest']}` | `{command}` | {item['caveat']} |"
        )
    lines.extend(
        [
            "",
            "## Merge completed reruns",
            "",
            "After a targeted rerun finishes, merge it into a new artifact rather than editing the historical lane in place:",
            "",
            "```bash",
            "python3.11 scripts/merge_paper_rerun_results.py \\",
            "  --base path/to/original/retrieval_guided_results.jsonl \\",
            "  --rerun path/to/rerun/retrieval_guided_results.jsonl \\",
            "  --out path/to/merged/retrieval_guided_results.jsonl",
            "```",
            "",
            "By default the merger only accepts rerun rows with no `error` and `score != not_run`, so failed rerun attempts do not overwrite usable base rows.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--include-empty", action="store_true")
    args = parser.parse_args()

    exports = export_manifests(args.out_dir, include_empty=args.include_empty)
    readme = write_readme(args.out_dir, exports)
    print(f"Wrote {len(exports)} rerun manifests under {args.out_dir}")
    print(f"Summary: {readme}")
    for item in exports:
        print(f"{item['count']:>3}  {item['lane']}  {item['manifest']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
